// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LazyComponentImport } from './routes/lazy-component'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as AdminIndexImport } from './routes/admin.index'
import { Route as AdminMembersImport } from './routes/admin.members'
import { Route as AdminMembersIndexImport } from './routes/admin.members.index'
import { Route as AdminMembersMemberIdImport } from './routes/admin.members.$memberId'

// Create/Update Routes

const LazyComponentRoute = LazyComponentImport.update({
  path: '/lazy-component',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminMembersRoute = AdminMembersImport.update({
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)

const AdminMembersIndexRoute = AdminMembersIndexImport.update({
  path: '/',
  getParentRoute: () => AdminMembersRoute,
} as any)

const AdminMembersMemberIdRoute = AdminMembersMemberIdImport.update({
  path: '/$memberId',
  getParentRoute: () => AdminMembersRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/lazy-component': {
      preLoaderRoute: typeof LazyComponentImport
      parentRoute: typeof rootRoute
    }
    '/admin/members': {
      preLoaderRoute: typeof AdminMembersImport
      parentRoute: typeof AdminImport
    }
    '/admin/': {
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/members/$memberId': {
      preLoaderRoute: typeof AdminMembersMemberIdImport
      parentRoute: typeof AdminMembersImport
    }
    '/admin/members/': {
      preLoaderRoute: typeof AdminMembersIndexImport
      parentRoute: typeof AdminMembersImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AdminRoute.addChildren([
    AdminMembersRoute.addChildren([
      AdminMembersMemberIdRoute,
      AdminMembersIndexRoute,
    ]),
    AdminIndexRoute,
  ]),
  LazyComponentRoute,
])
